CREATE TYPE attribute_type ('bool', 'num', 'string');

-- DDL generated by Postico 1.4.2
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE attributes (
    id SERIAL PRIMARY KEY,
    type attribute_type,
    name text,
    CONSTRAINT attributes_type_name_key UNIQUE (type, name)
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX attributes_pkey ON attributes(id int4_ops);
CREATE UNIQUE INDEX attributes_type_name_key ON attributes(type enum_ops,name text_ops);




-- DDL generated by Postico 1.4.2
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE model (
    id SERIAL PRIMARY KEY,
    name text NOT NULL UNIQUE
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX model_pkey ON model(id int4_ops);
CREATE UNIQUE INDEX model_name_key ON model(name text_ops);



-- DDL generated by Postico 1.4.2
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE model_attributes (
    id SERIAL PRIMARY KEY,
    model_id SERIAL REFERENCES model(id) ON DELETE CASCADE ON UPDATE CASCADE,
    attributes_id integer REFERENCES attributes(id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX model_attributes_pkey ON model_attributes(id int4_ops);
CREATE UNIQUE INDEX model_attributes_model_id_attributes_id_idx ON model_attributes(model_id int4_ops,attributes_id int4_ops);
